import { Callout, Card, Cards, Steps, Tabs } from "nextra/components";
import UniversalTabs from "@/components/UniversalTabs";
import { GithubSnippet, getSnippets } from "@/components/code";

export const OnFailureTs = {
  path: "src/v1/examples/on_failure/workflow.ts",
};

export const OnFailurePy = {
  path: "examples/on_failure/worker.py",
};

export const OnFailureGo = {
  path: "examples/on-failure/main.go",
};

export const getStaticProps = ({}) =>
  getSnippets([OnFailureTs, OnFailurePy, OnFailureGo]);

# On-Failure Tasks

The on-failure task is a special type of task in Hatchet workflows that allows you to define a function to be executed in the event that any task in the main workflow fails. This feature enables you to handle errors, perform cleanup tasks, or trigger notifications in case of workflow failures.

## Defining an on-failure task

You can define an on-failure task on your workflow the same as you'd define any other task:

<UniversalTabs items={["Python", "Typescript", "Go"]}>
  <Tabs.Tab title="Python">
    <GithubSnippet src={OnFailurePy} target="OnFailure Step" />
    <Callout variant="warning">
      Note: Only one on-failure task can be defined per workflow.
    </Callout>
  </Tabs.Tab>
  <Tabs.Tab title="Typescript">
    <GithubSnippet src={OnFailureTs} target="On Failure Task" />
  </Tabs.Tab>
  <Tabs.Tab title="Go">
    <GithubSnippet src={OnFailureGo} target="OnFailure Step" />
  </Tabs.Tab>
</UniversalTabs>

In the examples above, the on-failure task will be executed only if any of the main workflow task fail.

## Use Cases

Some common use cases for the on-failure task include:

- Performing cleanup tasks after a workflow failure
- Sending notifications or alerts about the failure
- Logging additional information for debugging purposes
- Triggering a compensating action or a fallback workflow

By utilizing the on-failure task, you can handle workflow failures gracefully and ensure that necessary actions are taken in case of errors.
